spring:
  application:
    name: onetomany-service
    
server:
# DEFAULT PORT IS 8671
  port: 9092 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka/
  instance:
    hostname: localhost
logging:
 level:
  com:
   netflix:
    eureka: OFF
    discovery: OFF
