zuul:
  prefix: /api
  routes:
   hello-server:
     path: /onetomany/**
     service-id:  onetomany-service
   hello-client:
     path: /order/**
     service-id: order-service


eureka:
  client:
    service-url:
     defaultZone: http://localhost:9090/eureka/
  instance:
    hostname: localhost
    
server:
  port: 9091
  
spring:
  application:
    name: zuul-service
     